name: Build Server Artifact

on:
  push:
    branches:
      - '*'
  workflow_dispatch:
    inputs:
      mindustry_commit:
        description: 'Commit SHA of the Mindustry upstream repository to build'
        required: true

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Patch Repo
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "RELEASE_TAG=${GITHUB_REF_NAME}-build" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$(date +'%Y.%m.%d').X${GITHUB_RUN_NUMBER}-${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12
          cache-read-only: false

      - name: Clone Mindustry at specified commit
        run: |
          git clone https://github.com/Anuken/Mindustry.git mindustry
          cd mindustry
          git checkout f21429f3f1c2b6be996fb9415661323705abc431

      - name: Apply patches
        run: |
          cd mindustry
          for patch in ../patches/*.patch; do
            echo "Applying $patch";
            git apply "$patch";
          done

      - name: Build server
        run: |
          cd mindustry
          ./gradlew -Pbuildversion=$RELEASE_VERSION server:dist

      - name: Collect artifact
        run: |
          mkdir -p artifacts
          mv mindustry/server/build/libs/server-release.jar artifacts/server-${RELEASE_VERSION}.jar

      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_VERSION }}
          target_commitish: ${{ github.sha }}
          files: artifacts/*
          prerelease: true
